name: clean_architecture
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-353.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:
  conditional_builder_null_safety:
  dio:
  http:
  fluttertoast:
  equatable:
  dartz:
  internet_connection_checker:
  shared_preferences:
  flutter_spinkit:
  get_it:


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
  fonts:
     - family: Tajawal
       fonts:
          - asset: assets/fonts/Tajawal-Medium.ttf
            weight: 500
          - asset: assets/fonts/Tajawal-Bold.ttf
            weight: 700
          - asset: assets/fonts/Tajawal-Black.ttf
            weight: 900
          - asset: assets/fonts/Tajawal-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Tajawal-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/Tajawal-Light.ttf
            weight: 300